import "./globals.css";
import { Toaster } from "sonner";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body
        className={`${poppins.className} min-h-full flex flex-col`}
      >
        {children}

        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
